投稿ページレイアウト作成
project-rqb/project-rqb-front pull request #38
Opened 2024-07-29 10:42 UTC by UNNNYOU

## 概要
画面遷移図を元にして質問投稿ページのレイアウトを作成しました。
また、質問投稿に伴ってzenn-editorの追加を行っています。

## 確認ポイント

- [x] タイトル入力欄
- [x] タグ入力欄
- [x] 本文入力欄
- [x] プレビュー欄
- [x] 投稿ボタン
- [x] ヘルプボタン
- [ ] サイドバー
  - [ ] ホーム
  - [ ] 質問
  - [ ] タグ
  - [ ] 未解決

## 補足
作成にあたり、多少のレイアウトの変更を行っています。
また、hooksにてレイアウトの改行に伴ってtextareaの高さを変更を行う処理を追加しましたので、投稿の際に必要性があれば使用を行ってください。

以下、参考の動画を表示しておきます
| PC | スマホ |
| --- | --- |
| [![Image from Gyazo](https://i.gyazo.com/eebf5521192ce6a964d5c47eb6861289.gif)](https://gyazo.com/eebf5521192ce6a964d5c47eb6861289) | [![Image from Gyazo](https://i.gyazo.com/de6a0e2f4a679863febe0d7ea9effe15.gif)](https://gyazo.com/de6a0e2f4a679863febe0d7ea9effe15) |

2024-07-29 11:17 UTC, topi0247 requested changes
ご対応ありがとうございます！
コメント残させていただいきました。
レビューアプリのデプロイが失敗しているのでビルドエラーが発生しているようです。
詳細はActionsのログから確認いただけますが抜粋すると下記でエラーが出ていますのでご確認いただければと思います。
手元で`docker compose build`して問題ないか確認していただけると良いかもしれません。
```bash
ReferenceError: HTMLElement is not defined
 at 5227 (/app/.next/server/chunks/952.js:30:15002)
 at t (/app/.next/server/webpack-runtime.js:1:128)
 at 36892 (/app/.next/server/chunks/952.js:30:15760)
 at t (/app/.next/server/webpack-runtime.js:1:128)
 at 17290 (/app/.next/server/chunks/40.js:1:9101)
 at t (/app/.next/server/webpack-runtime.js:1:128)
 at 55665 (/app/.next/server/app/(auth)/questions/page.js:1:2997)
 at Object.t [as require] (/app/.next/server/webpack-runtime.js:1:128)
 at require (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18365)
 at I (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362) {
 digest: '4207920916'
```

2024-07-29 11:17 UTC, topi0247 commented on src/utils/resizeTextarea/index.js
> +export function resizeTextArea(e) {
この関数を使う場所が1箇所だけだと推察しております。
悩ましいですがutilsよりかはコンポーネントに内包してしまってよいのではと思いました。

2024-07-29 11:17 UTC, topi0247 commented on src/app/(auth)/questions/new/page.jsx
> +  const body = useRecoilValue(questionBodyState);
titleとbodyをRecoilで管理する理由をお伺いしてもよいでしょうか？
formでどうにかならないかな～と思いました
https://ja.react.dev/reference/react-dom/components/form

2024-07-29 11:17 UTC, topi0247 commented on src/features/questions/components/questionBody/index.jsx
> +  const handlePreview = () => {
Previewの切り替えをしているので`togglePreview`とか如何でしょう？

2024-07-29 11:49 UTC, UNNNYOU commented
デプロイについては空き時間に確認します！
ちょっと、早急にやることがあるので少しだけお待ちいただけるとありがたいです！

2024-07-29 11:51 UTC, UNNNYOU commented on src/utils/resizeTextarea/index.js
> +export function resizeTextArea(e) {
ご確認ありがとうございます！
この関数については質問の回答時にも使用する可能性があると思い切り出しました！
一応、三浦さんと確認して使用する必要があるかどうかで、変更という形でも良いでしょうか？

2024-07-29 11:55 UTC, UNNNYOU commented on src/app/(auth)/questions/new/page.jsx
> +  const body = useRecoilValue(questionBodyState);
コンポーネントを分割した際、titleとbodyともに最後に入力された片方の値に統一されてしまった（bodyに入力するとtitleも同じ値になってしまった）ので、分割させていただきました！
もう少し調べれば上手い実装方法もあるかもしれないので、一旦調べ直してみます！！
参考URLありがとうございます！！

2024-07-29 11:57 UTC, UNNNYOU commented on src/features/questions/components/questionBody/index.jsx
> +  const handlePreview = () => {
なるほど！
確かにonとoffの機能であればhandleよりもtoggleの方がぱっと見でどういう機能かわかりそうですね！
修正します！ご確認ありがとうございます！

2024-07-29 12:28 UTC, topi0247 commented on src/app/(auth)/questions/new/page.jsx
> +  const body = useRecoilValue(questionBodyState);
グローバルに管理する必要はないと思うのでよろしくお願いします！

2024-07-29 12:28 UTC, topi0247 commented
了解ですー！

2024-08-04 06:59 UTC, topi0247 reviewed
ご対応ありがとうございます！
概ね良さそうな気がします！
もし対応可能でされば下記対応してくださるとUX向上するかなと思いますのでご検討いただければと思います。

テキストエリアの範囲が見かけに比べ狭いようで、ボックス下部をクリックしても入力になりませんでした。
範囲内をクリックしたらテキスト入力可能のほうが直感的な気がします。
よろしくお願いします！
[![Image from Gyazo](https://i.gyazo.com/ac33a018532339df05b5bc484e1d2409.gif)](https://gyazo.com/ac33a018532339df05b5bc484e1d2409)

2024-08-04 07:15 UTC, UNNNYOU commented
ん！？まじすか！？
環境差とかあるんですかね...？
僕の方だといけました！もしかしたら、サイズを一旦伸ばして戻すとエリアの幅が狭くなるかもです！
う〜ん、min-h-fullでやるとレイアウト崩れちゃうので考えてみます！！

[![Image from Gyazo](https://i.gyazo.com/71719b3c2363a1e8a1bbf1eecba83465.gif)](https://gyazo.com/71719b3c2363a1e8a1bbf1eecba83465)

2024-08-04 07:22 UTC, topi0247 commented
一応私のチェックはレビューアプリでしたので、そちらの方で確認してきょうへいさんの方問題なければ環境差っぽそうですね
ふむ…

2024-08-04 07:28 UTC, UNNNYOU commented
確認したところ、入力を行った際にはその文字の高さがtextareaの高さに変更されてますね
多分、resizeTextArea関数の影響ですね
そうしたら、ちょっと記載を変更しないと気持ちよく使えそうにないっすね〜
検討してみます！

2024-08-09 06:49 UTC, UNNNYOU commented
変更遅くなりすみません！修正しましたのでご確認よろしくお願いします！
[![Image from Gyazo](https://i.gyazo.com/6adb3a5ac096219a08748c29ca2bbf2a.gif)](https://gyazo.com/6adb3a5ac096219a08748c29ca2bbf2a)

2024-08-09 07:08 UTC, topi0247 approved these changes
ご対応ありがとございました！！
（もし余裕あったらREADMEの追加パッケージに追記お願いします🙏）
LGTMです！

2024-08-12 13:28 UTC, neko967 commented
LGTMです！！

2024-08-12 13:29 UTC, neko967 approved these changes
LGTMです！！

2024-08-16 13:52 UTC, merged